<?php

/**
 * @file
 * Contains custom_solr_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_solr_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_solr_search module.
    case 'help.page.custom_solr_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Solr Search') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_solr_search_theme($existing, $type, $theme, $path) {
  return array(
    'custom_solr_search_result' => array(
      'variables' => array(
        'url' => NULL,
        'title' => NULL,
        'author' => NULL,
        'publishDate' => NULL,
        'publisher' => NULL,
        'topic' => NULL,
        'docid' => NULL,
        'server' => NULL,
        'keyword' => NULL,
        'base_url' => NULL,
        'annotation' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'custom-solr-search-result',
    ),
    'custom_solr_search_facet' => array(
      'variables' => array(
        'facets' => NULL,
      ),
      'path' => $path . '/templates',
      'template' => 'custom-solr-search-facet',
    ),
  );
}

/**
 * Get url components
 *
 * @param string $component
 *   If defined only that component will be returned.
 *
 * @return array
 */
function custom_solr_search_get_url_components($component = NULL) {
  $url = $_SERVER['REQUEST_URI'];
  $url_array = explode('?', $url);
  $url_components['path'] = $url_array[0];
  $url_components['facet_query'] = [];
  $url_array = explode('&', $url_array[1]);
  foreach ($url_array as $params) {
    if (preg_match('/^_facet_.*/', $params)) {
      $params = str_replace('=', ':', str_replace('_facet_', '', $params));
      $url_components['facet_query'][] = $params;
    }
  }
  if ($component) {
    return $url_components[$component];
  }
  return $url_components;
}

function custom_solr_search_get_facet_field_settings() {
  return array(
    'Author' => 'author',
    'Publisher' => 'publisher',
    'Language' => 'language',
    'Institution' => 'institution',
    'Collection' => 'collection',
    'Publish date' => 'publishDate',
  );
}
